package UI;

import contextualTagger.ApplicationManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import utils.Pair;

/**
 *
 * @author Diego
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLearning = new javax.swing.JPanel();
        jSpinner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButtonTrainFile = new javax.swing.JButton();
        jLabelTrainFile = new javax.swing.JLabel();
        jButtonTrainFile2 = new javax.swing.JButton();
        jLabelTrainFile2 = new javax.swing.JLabel();
        jButtonSaveModel = new javax.swing.JButton();
        jButtonLearn = new javax.swing.JButton();
        jPanelTesting = new javax.swing.JPanel();
        jButtonTestFile = new javax.swing.JButton();
        jLabelTestFile = new javax.swing.JLabel();
        jButtonTest = new javax.swing.JButton();
        jPanelApplication = new javax.swing.JPanel();
        loadFileButton = new javax.swing.JButton();
        jButtonSaveResult = new javax.swing.JButton();
        jLabelAppFile = new javax.swing.JLabel();
        jButtonModelFile = new javax.swing.JButton();
        jLabelModelFile = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuEdit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLearning.setBorder(javax.swing.BorderFactory.createTitledBorder("Learning"));

        jLabel1.setText("Max. # of rules:");

        jButtonTrainFile.setText("Big training file");
        jButtonTrainFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrainFileActionPerformed(evt);
            }
        });

        jButtonTrainFile2.setText("Small training file");
        jButtonTrainFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrainFile2ActionPerformed(evt);
            }
        });

        jButtonSaveModel.setText("Save current model");
        jButtonSaveModel.setEnabled(false);
        jButtonSaveModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveModelActionPerformed(evt);
            }
        });

        jButtonLearn.setText("Learn");
        jButtonLearn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLearnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLearningLayout = new javax.swing.GroupLayout(jPanelLearning);
        jPanelLearning.setLayout(jPanelLearningLayout);
        jPanelLearningLayout.setHorizontalGroup(
            jPanelLearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLearningLayout.createSequentialGroup()
                .addGroup(jPanelLearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLearningLayout.createSequentialGroup()
                        .addGroup(jPanelLearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonTrainFile2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTrainFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTrainFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTrainFile2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelLearningLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelLearningLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanelLearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSaveModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLearn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanelLearningLayout.setVerticalGroup(
            jPanelLearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLearningLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelLearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTrainFile)
                    .addComponent(jLabelTrainFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLearningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTrainFile2)
                    .addComponent(jLabelTrainFile2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButtonLearn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSaveModel)
                .addContainerGap())
        );

        jPanelTesting.setBorder(javax.swing.BorderFactory.createTitledBorder("Testing"));

        jButtonTestFile.setText("Testing file");
        jButtonTestFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestFileActionPerformed(evt);
            }
        });

        jButtonTest.setText("Test");
        jButtonTest.setEnabled(false);
        jButtonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTestingLayout = new javax.swing.GroupLayout(jPanelTesting);
        jPanelTesting.setLayout(jPanelTestingLayout);
        jPanelTestingLayout.setHorizontalGroup(
            jPanelTestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTestingLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jButtonTest, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(jPanelTestingLayout.createSequentialGroup()
                .addComponent(jButtonTestFile, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTestFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        jPanelTestingLayout.setVerticalGroup(
            jPanelTestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTestingLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelTestingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTestFile)
                    .addComponent(jLabelTestFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonTest)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanelApplication.setBorder(javax.swing.BorderFactory.createTitledBorder("Application"));

        loadFileButton.setText("File");
        loadFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileButtonActionPerformed(evt);
            }
        });

        jButtonSaveResult.setText("Compute and save result");
        jButtonSaveResult.setEnabled(false);
        jButtonSaveResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelApplicationLayout = new javax.swing.GroupLayout(jPanelApplication);
        jPanelApplication.setLayout(jPanelApplicationLayout);
        jPanelApplicationLayout.setHorizontalGroup(
            jPanelApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApplicationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelApplicationLayout.createSequentialGroup()
                        .addComponent(loadFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelAppFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelApplicationLayout.createSequentialGroup()
                        .addComponent(jButtonSaveResult)
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelApplicationLayout.setVerticalGroup(
            jPanelApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelApplicationLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelApplicationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadFileButton)
                    .addComponent(jLabelAppFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSaveResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonModelFile.setText("Model file");
        jButtonModelFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModelFileActionPerformed(evt);
            }
        });

        jMenuFile.setText("File");
        jMenuBar.add(jMenuFile);

        jMenuEdit.setText("Edit");
        jMenuBar.add(jMenuEdit);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLearning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTesting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonModelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelModelFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelApplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLearning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelApplication, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModelFile)
                            .addComponent(jLabelModelFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelTesting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrainFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrainFileActionPerformed
        jFileChooser.showOpenDialog(this);
        trainFile = jFileChooser.getSelectedFile();
        jLabelTrainFile.setText(trainFile.getName());
    }//GEN-LAST:event_jButtonTrainFileActionPerformed

    private void jButtonTrainFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrainFile2ActionPerformed
        jFileChooser.showOpenDialog(this);
        trainFile2 = jFileChooser.getSelectedFile();
        jLabelTrainFile2.setText(trainFile2.getName());
    }//GEN-LAST:event_jButtonTrainFile2ActionPerformed

    private void jButtonLearnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLearnActionPerformed
        try {
            jButtonSaveModel.setEnabled(false);
            model = contextualTagger.LearningManager.learn(trainFile, trainFile2, Integer.parseInt(jSpinner.getModel().getValue() + ""));
            jButtonSaveModel.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception e) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButtonLearnActionPerformed

    private void jButtonSaveModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveModelActionPerformed
        jFileChooser.showSaveDialog(this);
        File file = jFileChooser.getSelectedFile();
        try {
            FileOutputStream fileOut
                    = new FileOutputStream(file);
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(model);
            out.close();
            fileOut.close();
        } catch (IOException i) {
            i.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaveModelActionPerformed

    private void jButtonTestFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestFileActionPerformed
        jFileChooser.showOpenDialog(this);
        testFile = jFileChooser.getSelectedFile();
        jLabelTestFile.setText(testFile.getName());
    }//GEN-LAST:event_jButtonTestFileActionPerformed

    private void jButtonModelFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModelFileActionPerformed
        jButtonTest.setEnabled(false);
        jFileChooser.showOpenDialog(this);
        modelFile = jFileChooser.getSelectedFile();
        jLabelModelFile.setText(modelFile.getName());
        model = null;
        try {
            FileInputStream fileIn = new FileInputStream(modelFile);
            ObjectInputStream in = new ObjectInputStream(fileIn);
            model = (contextualTagger.Model) in.readObject();
            in.close();
            fileIn.close();
        } catch (IOException i) {
            i.printStackTrace();
            return;
        } catch (ClassNotFoundException c) {
            System.out.println("Model class not found");
            c.printStackTrace();
            return;
        }
        jButtonTest.setEnabled(true);
        if (model != null && appFile != null) {
            jButtonSaveResult.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonModelFileActionPerformed

    private void jButtonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTestActionPerformed
        try {
            contextualTagger.TestingManager.test(testFile, model);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTestActionPerformed

    private void loadFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileButtonActionPerformed
        jFileChooser.showOpenDialog(this);
        appFile = jFileChooser.getSelectedFile();
        jLabelAppFile.setText(appFile.getName());
        if (model != null && appFile != null) {
            jButtonSaveResult.setEnabled(true);
        }
    }//GEN-LAST:event_loadFileButtonActionPerformed

    private void jButtonSaveResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveResultActionPerformed
        jFileChooser.showSaveDialog(this);
        File file = jFileChooser.getSelectedFile();
        try {
            result = ApplicationManager.applyModel(appFile, model);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            PrintWriter out = new PrintWriter(file);
            for (Pair<String, String> p : result) {
                out.println(p.first + " " + p.second);
            }
            out.close();
        } catch (IOException i) {
            i.printStackTrace();
        }
    }//GEN-LAST:event_jButtonSaveResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(
                            UIManager.getSystemLookAndFeelClassName());
                } catch (UnsupportedLookAndFeelException e) {
                } catch (ClassNotFoundException e) {
                } catch (InstantiationException e) {
                } catch (IllegalAccessException e) {
                }
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLearn;
    private javax.swing.JButton jButtonModelFile;
    private javax.swing.JButton jButtonSaveModel;
    private javax.swing.JButton jButtonSaveResult;
    private javax.swing.JButton jButtonTest;
    private javax.swing.JButton jButtonTestFile;
    private javax.swing.JButton jButtonTrainFile;
    private javax.swing.JButton jButtonTrainFile2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAppFile;
    private javax.swing.JLabel jLabelModelFile;
    private javax.swing.JLabel jLabelTestFile;
    private javax.swing.JLabel jLabelTrainFile;
    private javax.swing.JLabel jLabelTrainFile2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JPanel jPanelApplication;
    private javax.swing.JPanel jPanelLearning;
    private javax.swing.JPanel jPanelTesting;
    private javax.swing.JSpinner jSpinner;
    private javax.swing.JButton loadFileButton;
    // End of variables declaration//GEN-END:variables
    private JFileChooser jFileChooser = new JFileChooser(new File(System.getProperty("user.dir")));
    private File trainFile, trainFile2, testFile, modelFile, appFile;
    private contextualTagger.Model model;
    private List<Pair<String, String>> result;
}
